"use strict";
/* ═══════════════════════════════════════════════════════════════
   data.js — Pure data constants (no DOM, no side effects)
   ═══════════════════════════════════════════════════════════════ */

var RULE_TEXTS = [
  "R1 \u00b7 Assumptions First: State all assumptions explicitly (instrument, timeframe, Strategy vs Indicator context) before writing any code.",
  "R2 \u00b7 Scope Lock: Do NOT modify, refactor, or rewrite any code outside the scope of the current request.",
  "R3 \u00b7 Code Labels: Present all code in file-path-labeled fenced code blocks (e.g., ```csharp // NinjaTrader 8 / Strategies/MyStrategy.cs```).",
  "R4 \u00b7 Checkpoints: After each unit, provide a checkpoint: \u2705 Built, \u23ed Skipped, \ud83d\udd1c Next.",
  "R5 \u00b7 Wait for Approval: Wait for explicit user approval before proceeding to the next unit unless told otherwise.",
  "R6 \u00b7 No API Hallucination: Do NOT hallucinate or fabricate NinjaTrader 8 APIs. If unsure whether a method or overload exists, say so and recommend verification in the NT8 Help Guide.",
  "R7 \u00b7 No Fake Results: Do NOT hallucinate backtest results. If tests cannot be executed, state: \"Backtest logic written but not executed \u2014 run in Strategy Analyzer to verify.\"",
  "R8 \u00b7 Priority Hierarchy: Security \u2192 Correctness \u2192 Reliability \u2192 Performance \u2192 Usability \u2192 Maintainability.",
  "R9 \u00b7 Flag Limitations: Flag all known limitations: \"\u26a0\ufe0f Limitation: [desc]. Recommend: [mitigation].\"",
  "R10 \u00b7 NS Conventions: Follow NinjaScript/C# conventions: PascalCase class names matching filename, camelCase private fields, [Range] attributes on parameters.",
  "R11 \u00b7 No Credentials: No hardcoded account credentials, API keys, or license keys in code.",
  "R12 \u00b7 No Sensitive Logs: Never log sensitive data (account numbers, positions, balances) via Print() in production code.",
  "R13 \u00b7 Input Validation: Validate all inputs: guard CurrentBar >= N before accessing series[N], null-check Position/Orders/Account objects.",
  "R14 \u00b7 Self-Documenting: Write self-documenting code. Comments explain WHY and include formula sources. No magic numbers \u2014 expose all constants as [NinjaScriptProperty] parameters."
];

var SCALE_TEXTS = {
  micro: "\u26a1 MICRO \u2014 Single indicator, quick utility, or prototype.\n \u2022 Inline comments only.\n \u2022 Manual testing OK.\n \u2022 Minimal documentation.\n \u2022 Focus on correct logic, not production hardening.",
  small: "\ud83d\udd27 SMALL \u2014 Single strategy with basic risk management.\n \u2022 Test edge cases (flat open, partial fills, connection loss).\n \u2022 Document all assumptions.\n \u2022 Include OnBarUpdate() + OnExecutionUpdate() separation.\n \u2022 Basic backtest validation required.",
  medium: "\ud83d\udce6 MEDIUM \u2014 Multi-strategy system or strategy + custom indicators.\n \u2022 Full documentation and architecture notes.\n \u2022 Backtest validation with walk-forward analysis.\n \u2022 State machine design (Flat/Long/Short/PendingEntry/PendingExit).\n \u2022 Performance review required.\n \u2022 9-item deliverable checklist per feature.",
  large: "\ud83c\udfd7\ufe0f LARGE \u2014 Production live trading system.\n \u2022 Prop firm compliance (trailing drawdown, daily limits, reset logic).\n \u2022 Full deployment checklist.\n \u2022 DLL/dependency management documented.\n \u2022 Alert thresholds defined (max drawdown, max daily loss, max consecutive losses).\n \u2022 Incident response: flatten on unexpected state.\n \u2022 Zero compiler warnings policy.\n \u2022 Git conventions enforced."
};

var DOMAIN_TEXTS = {
  execution: "\u2694\ufe0f EXECUTION & ORDERS\n \u2022 Use EnterLong/Short for market orders. Use EnterLongLimit/StopMarket for precision.\n \u2022 Always name orders for tracking (e.g., \"MyEntryLong\").\n \u2022 Track fills in OnExecutionUpdate() \u2014 never assume instant fill.\n \u2022 Use Position.MarketPosition and Position.Quantity \u2014 never manually track position with counters.\n \u2022 Set realistic Slippage and CommissionsInfo in backtest properties.\n \u2022 Handle partial fills and order rejections explicitly.",
  risk: "\ud83d\udee1\ufe0f RISK MANAGEMENT\n \u2022 Prefer SetStopLoss() and SetProfitTarget() over manual order management where possible.\n \u2022 Implement DailyLoss variable updated in OnExecutionUpdate(). Halt trading when breached.\n \u2022 Define max positions and enforce in code.\n \u2022 For prop firms: implement trailing drawdown logic in code \u2014 never rely solely on platform-level limits.\n \u2022 Define alert thresholds: max acceptable drawdown, max daily loss, max consecutive losses.",
  indicators: "\ud83d\udcca INDICATORS & SIGNALS\n \u2022 Declare all output series in OnStateChange(State.Configure) with AddPlot() or AddLine().\n \u2022 Use CurrentBar guards: if (CurrentBar < minBarsRequired) return;\n \u2022 Set BarsRequiredToPlot and BarsRequiredToTrade appropriately \u2014 default 20 is rarely sufficient.\n \u2022 Cache indicator references (EMA, ATR, etc.) in private fields during State.DataLoaded \u2014 do NOT instantiate in OnBarUpdate().\n \u2022 Avoid LINQ, string interpolation, and allocations in the hot path.",
  evaluation: "\ud83e\uddea EVALUATION STANDARDS & STATISTICAL REVIEW\n \u2022 NON-EXECUTABLE: The AI must NOT execute backtests or fetch market data.\n \u2022 All performance results must originate from an external engine (NinjaTrader, Python, TradingView, or equivalent).\n \u2022 The AI\u2019s role is to REVIEW, VALIDATE, and CRITIQUE supplied results only.\n \u2022 Require evidence of sufficient historical evaluation (\u2265 6 months unless justified). Flag statistical unreliability if the dataset is too small.\n \u2022 Evaluate execution assumptions (Tick Replay, bar-close fills, etc.). Flag results as unverified if execution model is unspecified.\n \u2022 Require explicit In-Sample / Out-of-Sample separation (\u2265 20% OOS preferred). Flag any optimization performed on the full dataset as invalid.\n \u2022 Verify positive expectancy: (WinRate \u00d7 AvgWin) - (LossRate \u00d7 AvgLoss) > 0. High win rate alone must NOT be treated as proof of edge.\n \u2022 Review Monte Carlo results if provided; focus on worst-case drawdowns and sequence sensitivity. Recommend Monte Carlo analysis if sequence risk is unexamined.\n \u2022 Require live-equivalent validation evidence (Market Replay / SIM). Backtest-only results must be labeled as incomplete.\n \u2022 Require confirmation that indicator math was externally verified (Python/Excel). Platform indicators must not be blindly trusted.\n \u2022 The AI must NEVER invent, simulate, or fabricate performance metrics. Missing results must be explicitly stated \u2014 never approximated.",
  performance: "\u26a1 PERFORMANCE\n \u2022 No allocations in hot path: no new[], List<T>, LINQ, or string interpolation inside OnBarUpdate() or OnTick().\n \u2022 Cache indicator references in private fields during initialization.\n \u2022 Store frequently accessed values (Close[0], High[0]) in local variables at top of OnBarUpdate().\n \u2022 Use IsFirstTickOfBar for strategies that only act once per bar.\n \u2022 Never call Thread.Sleep() or synchronous HTTP/file I/O on the NT8 event thread.\n \u2022 Wrap Print()/Log() in #if DEBUG or behind [NinjaScriptProperty] bool debugMode.",
  session: "\ud83d\udd50 SESSION & TIMING\n \u2022 Define session scope: 24-hr, RTH only, or custom session templates.\n \u2022 Use BarsInProgress to control multi-series logic. Default series = 0.\n \u2022 Implement time-of-day filters (e.g., only trade 9:30 AM \u2013 3:30 PM ET).\n \u2022 Implement flat-at-close logic to avoid overnight positions.\n \u2022 Handle session reset: reset daily P&L counters, trade counts, and state flags.\n \u2022 Test with session break data (e.g., Globex vs RTH transitions).",
  mtf: "\ud83d\udcd0 MULTI-TIMEFRAME\n \u2022 Declare all secondary series via AddDataSeries() in State.Configure. Never add series dynamically at runtime.\n \u2022 Guard every series independently: if (CurrentBars[0] < minBars || CurrentBars[1] < minBars) return;\n \u2022 Use BarsInProgress to route logic: 0 = primary series, 1+ = secondary series. Always check BarsInProgress at the top of OnBarUpdate().\n \u2022 Access secondary series data via plural accessors: Closes[1][0], Highs[1][0], Lows[1][0], Opens[1][0], Volumes[1][0], Times[1][0].\n \u2022 Do NOT use Close[0] to read secondary series \u2014 that always refers to BarsInProgress == 0.\n \u2022 Cache secondary indicator references per BarsInProgress index during State.DataLoaded (e.g., emaHTF = EMA(Closes[1], 20)).\n \u2022 Cross-timeframe pattern: compute higher-TF condition in its own BarsInProgress block, store in a bool/variable, then reference it in the primary series block for entry/exit decisions.\n \u2022 Be aware of bar-alignment: a daily bar closes once while multiple intraday bars fire. Use IsFirstTickOfBar where appropriate.\n \u2022 Enable Tick Replay if sub-bar precision matters for secondary series signals.\n \u2022 Common pitfall: accessing Closes[1][0] before the secondary series has enough bars \u2014 always guard with CurrentBars[1] >= N."
};

var STRATEGY_TYPE_TEXTS = {
  meanReversion: "\ud83d\udd04 STRATEGY TYPE: MEAN REVERSION\n  \u2022 Philosophy: Price deviates from a statistical mean and tends to revert. Fade extremes, exit on return to equilibrium.\n  \u2022 Core indicators: Bollinger Bands, RSI, Stochastic Oscillator, Z-Score, Keltner Channels, VWAP.\n  \u2022 Entry logic: Enter counter-trend when price touches or exceeds outer bands/thresholds (e.g., lower Bollinger Band touch for long, RSI < 30).\n  \u2022 Exit logic: Exit on return to the mean (midline, moving average, VWAP) or on a time-based expiry.\n  \u2022 Risk: Strong trending markets cause extended drawdowns. Always include a max adverse excursion stop-loss.\n  \u2022 Filters: Add a regime/range filter (e.g., ADX < 25) to avoid trading mean-reversion signals in trending conditions.\n  \u2022 Considerations: Works best in range-bound or choppy markets. Define lookback period and deviation thresholds as [NinjaScriptProperty] parameters.\n  \u2022 Common pitfall: Over-optimization of band width or lookback \u2014 validate with walk-forward analysis.",
  trendFollowing: "\ud83d\udcc8 STRATEGY TYPE: TREND FOLLOWING\n  \u2022 Philosophy: Identify established trends and ride momentum until reversal signals appear. Let winners run, cut losers fast.\n  \u2022 Core indicators: Moving Average crossovers (EMA/SMA), ADX/DMI, MACD, Donchian Channels, Parabolic SAR, Supertrend.\n  \u2022 Entry logic: Enter in the direction of the trend on confirmation (e.g., fast EMA crosses above slow EMA, ADX > 25 with +DI > -DI).\n  \u2022 Exit logic: Exit on trend reversal signal (opposing crossover, ADX declining) or use trailing stops (ATR-based or chandelier exit).\n  \u2022 Risk: Whipsaws and false signals in ranging/choppy markets. Expect lower win rate but larger average wins.\n  \u2022 Filters: Add a trend-strength filter (e.g., ADX > 20) and avoid entry during low-volatility consolidation zones.\n  \u2022 Considerations: Works best in markets with sustained directional moves. Define trend confirmation period and trailing stop multiplier as [NinjaScriptProperty] parameters.\n  \u2022 Common pitfall: Late entries on exhausted trends \u2014 consider adding momentum confirmation (e.g., ROC or MACD histogram direction).",
  breakout: "\ud83d\udca5 STRATEGY TYPE: BREAKOUT\n  \u2022 Philosophy: Price consolidates in a range, then expands directionally. Enter on the range break, target continuation.\n  \u2022 Core indicators: Donchian Channels, horizontal support/resistance levels, ATR (for volatility expansion), Volume, Squeeze Momentum.\n  \u2022 Entry logic: Enter when price breaks above resistance or below support (e.g., new N-bar high/low via Donchian, or break of prior session high/low).\n  \u2022 Exit logic: ATR-based profit targets, trailing stop once in profit, or exit on failed breakout (price returns inside the range).\n  \u2022 Risk: False breakouts are the primary enemy. Many breakouts fail and reverse back into the range.\n  \u2022 Filters: Add volume confirmation (volume spike on breakout bar), time-of-day filters (avoid thin liquidity periods), and minimum consolidation duration.\n  \u2022 Considerations: Works best after periods of compression/low volatility. Define breakout lookback period, ATR multiplier for targets, and minimum range duration as [NinjaScriptProperty] parameters.\n  \u2022 Common pitfall: Entering on noise spikes \u2014 require bar close beyond level or a minimum tick distance past the breakout point.",
  scalping: "\u26a1 STRATEGY TYPE: SCALPING\n  \u2022 Philosophy: Capture small, rapid profits from micro price movements. Quick in, quick out \u2014 minimize market exposure.\n  \u2022 Core indicators: Level 2/DOM, Tick charts, Volume Profile, VWAP, EMA (very short periods), Order Flow, Time & Sales.\n  \u2022 Entry logic: Enter on micro-momentum shifts, tape reading signals, or rapid mean-reversion on ultra-short timeframes (e.g., tick/1-min charts).\n  \u2022 Exit logic: Tight fixed-point or tick-based profit targets. Immediate stop-loss. Time-based exit if target not reached within N bars.\n  \u2022 Risk: Commissions and slippage can erode edge quickly. Requires fast execution and low latency. Small per-trade edge demands high consistency.\n  \u2022 Filters: Session/time-of-day filters (trade only high-volume periods), spread filters, minimum volatility thresholds.\n  \u2022 Considerations: Works best in highly liquid instruments (ES, NQ, CL). Define tick-based targets, stops, and max trades per session as [NinjaScriptProperty] parameters.\n  \u2022 Common pitfall: Overtrading \u2014 define max trades per session. Commission drag makes marginal edges unprofitable."
};


var SESSION_TEXTS = {
  asia: "\ud83c\udf0f ASIA SESSION\n \u2022 Hours: 6:00 PM \u2013 2:00 AM ET\n \u2022 Covers Tokyo, Sydney, and broader Asian markets.\n \u2022 Typically lower volatility with range-bound price action.\n \u2022 Suitable for mean-reversion and low-volatility scalping strategies.\n \u2022 Define session start/end times as [NinjaScriptProperty] parameters.",
  london: "\ud83c\udf0d LONDON SESSION\n \u2022 Hours: 2:00 AM \u2013 8:00 AM ET\n \u2022 Covers London, Frankfurt, and European markets.\n \u2022 Often produces breakout moves as European liquidity enters.\n \u2022 Late overlap with Asia session can generate strong directional setups.\n \u2022 Define session start/end times as [NinjaScriptProperty] parameters.",
  newYork: "\ud83c\udf0e NEW YORK SESSION\n \u2022 Hours: 8:00 AM \u2013 5:00 PM ET\n \u2022 Covers US equity and futures markets.\n \u2022 Highest liquidity period, especially during London/NY overlap (8:00 AM \u2013 12:00 PM ET).\n \u2022 Key economic releases and news events drive volatility in this window.\n \u2022 Define session start/end times as [NinjaScriptProperty] parameters."
};

var PRESETS = {
  strategy: { scale: "small", domains: ["execution", "risk", "evaluation"] },
  indicator: { scale: "micro", domains: ["indicators", "performance"] },
  propfirm: { scale: "medium", domains: ["execution", "risk", "session", "evaluation"] }
};

var TS_LABELS = {
  compile: "\ud83d\udd34 NinjaScript Compile Error",
  backtest: "\ud83d\udcca Backtest Discrepancy",
  livesim: "\u26a1 Live vs Sim Divergence",
  orderfill: "\ud83d\udccb Order Fill Issue",
  indicator: "\ud83d\udd22 Indicator Calculation Bug",
  perf: "\ud83d\udc0c Performance / Lag"
};

var TS_DESCS = {
  compile: "NinjaScript code fails to compile in NinjaTrader 8. Error shows in Output window or compile dialog.",
  backtest: "Backtest results in Strategy Analyzer don\'t match expected behavior or manual trade review.",
  livesim: "Strategy behaves differently in live/sim execution vs backtest. Fills, timing, or signals diverge.",
  orderfill: "Orders not filling, double fills, wrong quantity, or unexpected order states in OnOrderUpdate/OnExecutionUpdate.",
  indicator: "Indicator values are incorrect, not plotting, or don\'t match reference calculations (Python/Excel).",
  perf: "Strategy or indicator causing UI lag, slow chart loading, or excessive CPU usage during processing."
};
